project:
  type: website
  output-dir: docs

website:
  # title: "CONICET_serie_historica"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      # - href: about.qmd
      #   text: Acerca de
    right:

      - icon: linkedin
        href: https://www.linkedin.com/in/fedegiovannetti/
        
      - icon: envelope
        href: mailto:giovannettipsi@gmail.com
        
      - icon: book
        href: https://scholar.google.es/citations?user=O257bnQAAAAJ&hl=es
        
      - icon: github
        menu:
          - text: Código fuente
            href: https://github.com/FedeGiovannetti/CONICET_serie_historica
          - text: Reportar un error
            href: https://github.com/FedeGiovannetti/CONICET_serie_historica/issues

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  echo: false
  message: false
  warning: false

