project:
  type: website
  output-dir: docs

website:
  # title: "CONICET_serie_historica"
  google-analytics: "G-LBP73MEE67"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: analisis_todas_las_areas.qmd
        text: Análisis general
      - href: analisis_ks.qmd
        text: Análisis sociales y humanidades
      # - href: about.qmd
      #   text: Acerca de
    right:

      - icon: linkedin
        href: https://www.linkedin.com/in/fedegiovannetti/
        
      - icon: envelope
        href: mailto:giovannettipsi@gmail.com
        
      - icon: book
        href: https://scholar.google.es/citations?user=O257bnQAAAAJ&hl=es
        
      - icon: github
        menu:
          - text: Código fuente
            href: https://github.com/FedeGiovannetti/CONICET_serie_historica
          - text: Reportar un error
            href: https://github.com/FedeGiovannetti/CONICET_serie_historica/issues
  sidebar:
    contents:
      - section: "Series históricas"
        contents:
          - analisis_todas_las_areas.qmd
          - analisis_ks.qmd
          
          - text: "Análisis Comisión de psicología y Ciencias de la Educación (KS7)"
            href: https://fedegiovannetti.github.io/ks7conicet/
          - text: "Análisis temáticas sobre desarrollo infantil"
            href: https://github.com/AgendasDesarrolloInfantil/Smulski_et_al_2023


format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  echo: false
  message: false
  warning: false

