---
title: "Series históricas e información sobre becas (doctorales y postdoctorales) e investigadores del CONICET"
---

Este repo incluye datos sobre la cantidad de becas doctorales y posdoctorales e ingresos CIC otorgados por el CONICET a lo largo de los años. 
Pueden visualizar algunos de estos datos en [https://fedegiovannetti.github.io/CONICET_serie_historica/](https://fedegiovannetti.github.io/CONICET_serie_historica/)

Los valores mostrados son los anunciados por CONICET en su página al momento de la publicación de resultados. Estos valores no incluyen las posibles diferencias por becas adjudicadas, bajas, reconsideraciones u otros. 

Actualmente los datos se muestran para las convocatorias de Temas Generales y Temas Estratégicos. Próximamente se incluirán otro tipo de convocatorias (e.g. fortalecimiento) asi como también los ingresos CIC. En algunos casos puede haber datos faltantes por haber encontrado errores, inconsistencias o simplemente no haber encontrado datos en los registros del organismo. Todos los datos son abiertos y estan disponibles en el [repo](https://github.com/FedeGiovannetti/CONICET_serie_historica).

La página y el repo son mantenidos por [Federico Giovannetti](https://linktr.ee/fedegiova). Forma parte del proyecto de Agendas Científicas impulsado junto con [Mariana Smulski](https://bicyt.conicet.gov.ar/fichas/p/mariana-celeste-smulski). Los datos del Gran Área de Ciencias Sociales y Humanidades fueron recabados junto con [Fernando Gonzalez Cantero](https://www.linkedin.com/in/fernando-gonzalez-cantero-b3108a4b). Los datos sobre diferencias de género fueron trabajados junto con [Neurotransmitiendo](https://www.instagram.com/neurotransmitiendo/).


En la barra de la izquierda podrán ver, además de las series históricas actualizadas, algunos proyectos relacionados.

